---
name: Continuous Integration Build

on:
    push:
        branches:
            - master
            - 3.x
        paths-ignore:
            - '.github/**'

jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                java: [
                    {'version': '8', 'source': 'releases'},
                    {'version': '11', 'source': 'releases'},
                    {'version': '14', 'source': 'releases'}
#                    {'version': '15', 'source': 'nightly'}
                ]
        name: Build with Java ${{ matrix.java.version }}
        steps:
            - uses: actions/cache@v2
              with:
                  path: ~/.m2/repository
                  key: maven-${{ hashFiles('**/pom.xml') }}
                  restore-keys: |
                      maven-
            - uses: actions/checkout@v2
            - uses: AdoptOpenJDK/install-jdk@v1
              with:
                  version: ${{ matrix.java.version }}
                  source: ${{ matrix.java.source }}
            - name: Build with Maven
              run: |
                  mvn -B clean verify -Dtest-containers=true --file pom.xml

    quality:
        needs: build
        runs-on: ubuntu-latest
        steps:
            - uses: actions/cache@v2
              with:
                path: ~/.m2/repository
                key: maven-${{ hashFiles('**/pom.xml') }}
                restore-keys: |
                    maven-
            - uses: actions/checkout@v2
            - uses: AdoptOpenJDK/install-jdk@v1
              with:
                version: 11
                source: 'releases'
            - name: Coverage and Sonar
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  SONAR_TOKEN: ${{ secrets.SONAR_LOGIN }}
              run: |
                    mvn -B clean verify sonar:sonar -Pcoverage \
                        -Dsonar.projectKey=smallrye_smallrye-reactive-messaging \
                        -Dsonar.projectName="SmallRye Reactive Messaging" \
                        -Dsonar.organization=smallrye \
                        -Dsonar.host.url=https://sonarcloud.io \
                        -Dsonar.login=$SONAR_LOGIN \
                        --fail-at-end

    up_to_date_antora:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: AdoptOpenJDK/install-jdk@v1
              with:
                  version: 11
                  source: 'releases'
            - name: Build with Maven
              # Fail the build is the antora.yaml becomes out of date
              run: |
                  mvn -B install -DskipTests
                  mvn -B -pl documentation scm:check-local-modification \
                     -Dincludes=src/main/doc/antora.yml
